import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header/Header'
import Rodape from '@/components/rodape/Rodape'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-br">
            <body>
                <Header />
                {children}
                <Rodape />
            </body>
        </html>
    )
}
